import { useEffect, useState } from 'react'
import { Archive, CheckCircle2, Download, FileJson, FileSpreadsheet, RefreshCw, ShieldCheck } from 'lucide-react'
import { createWorkspaceBackup, downloadCsv, downloadJson } from '../../lib/backup'
import { getWorkspaceMembers } from '../../lib/workspace'
import RestoreBackup from './RestoreBackup'

export default function Backup({ user }) {
  const [busy,setBusy]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [isAdmin,setIsAdmin]=useState(false)
  useEffect(()=>{let active=true;getWorkspaceMembers(user.id).then(d=>active&&setIsAdmin(d.myRole==='admin')).catch(e=>active&&setError(e.message||'Gagal memeriksa akses workspace.'));return()=>{active=false}},[user.id])
  const run=async type=>{setBusy(type);setMessage('');setError('');try{const b=await createWorkspaceBackup(user.id);const stamp=new Date().toISOString().slice(0,10);if(type==='json')downloadJson(b,`wsaku-backup-${stamp}.json`);else if(type==='transactions')downloadCsv(b.transactions,`wsaku-transaksi-${stamp}.csv`);else if(type==='transfers')downloadCsv(b.transfers,`wsaku-transfer-${stamp}.csv`);else if(type==='accounts')downloadCsv(b.accounts,`wsaku-akun-${stamp}.csv`);else downloadCsv(b.categories,`wsaku-kategori-${stamp}.csv`);setMessage('File berhasil dibuat dan diunduh.')}catch(e){setError(e.message||'Gagal membuat export.')}finally{setBusy('')}}
  const Action=({type,icon:Icon,title,text})=><button onClick={()=>run(type)} disabled={!!busy} className="group flex w-full items-center gap-4 rounded-2xl border border-slate-800 bg-slate-950/50 p-4 text-left transition hover:border-slate-700 disabled:opacity-50"><div className="rounded-xl bg-blue-500/10 p-3 text-blue-300"><Icon size={20}/></div><div className="min-w-0 flex-1"><p className="font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>{busy===type?<RefreshCw className="animate-spin text-slate-500" size={17}/>:<Download size={17} className="text-slate-600 transition group-hover:text-slate-300"/>}</button>
  return <main className="min-h-screen bg-slate-950 text-slate-100"><div className="mx-auto max-w-4xl px-4 py-6 pb-24 md:px-6 md:py-8"><p className="text-sm text-slate-500">Data & Pemulihan</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Export & Backup</h1><p className="mt-1 text-sm text-slate-500">Simpan dan pulihkan data workspace secara lokal.</p>{error&&<div role="alert" className="mt-4 rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}{message&&<div role="status" className="mt-4 flex items-center gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-300"><CheckCircle2 size={17}/>{message}</div>}<section className="mt-6 rounded-2xl border border-blue-500/15 bg-blue-500/5 p-5"><div className="flex items-start gap-3"><ShieldCheck className="shrink-0 text-blue-300" size={20}/><div><h2 className="font-semibold">Backup workspace</h2><p className="mt-1 text-sm leading-6 text-slate-500">Backup JSON berisi workspace, akun, kategori, transaksi, transfer, dan metadata membership.</p></div></div></section><section className="mt-6 grid gap-3"><Action type="json" icon={Archive} title="Backup Lengkap · JSON" text="Seluruh data workspace dalam satu file arsip."/><Action type="transactions" icon={FileSpreadsheet} title="Transaksi · CSV" text="Pemasukan dan pengeluaran untuk Excel/Spreadsheet."/><Action type="transfers" icon={FileSpreadsheet} title="Transfer · CSV" text="Seluruh transfer antar akun."/><Action type="accounts" icon={FileSpreadsheet} title="Akun Keuangan · CSV" text="Daftar akun, saldo awal, dan status."/><Action type="categories" icon={FileJson} title="Kategori · CSV" text="Daftar kategori pemasukan dan pengeluaran."/></section><RestoreBackup user={user} isAdmin={isAdmin}/><div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Catatan keamanan</h2><p className="mt-2 text-sm leading-6 text-slate-500">Export mengikuti akses workspace pengguna yang sedang login. Tidak ada service-role key yang digunakan di browser.</p></div></div></main>
}
