import { useRef, useState } from 'react'
import { AlertTriangle, CheckCircle2, FileUp, RefreshCw } from 'lucide-react'
import { restoreWorkspaceBackup } from '../../lib/backup'

export default function RestoreBackup({ user, isAdmin }) {
  const inputRef = useRef(null)
  const [backup,setBackup]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
  const choose=e=>{setMessage('');setError('');const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d?.app!=='WSaku Pro'||d?.schema_version!==1)throw new Error('File bukan backup WSaku Pro versi yang didukung.');if(!d.workspace?.id)throw new Error('Identitas workspace tidak ditemukan.');setBackup(d)}catch(x){setBackup(null);setError(x.message||'JSON tidak valid.')}};r.onerror=()=>setError('File tidak dapat dibaca.');r.readAsText(file);e.target.value=''}
  const restore=async()=>{if(!backup||!isAdmin)return;if(!window.confirm('Lanjutkan restore ke workspace aktif? Data yang tidak ada di backup tidak akan dihapus.'))return;setBusy(true);setError('');setMessage('');try{const r=await restoreWorkspaceBackup(user.id,backup);setMessage(`Restore selesai: ${r?.restored_items??0} item diproses.`);setBackup(null)}catch(e){setError(e.message||'Restore gagal.')}finally{setBusy(false)}}
  return <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start gap-3"><div className="rounded-xl bg-amber-500/10 p-3 text-amber-300"><FileUp size={19}/></div><div><h2 className="font-semibold">Import / Restore</h2><p className="mt-1 text-sm leading-6 text-slate-500">Pulihkan data dari backup JSON. Hanya Admin workspace yang dapat menjalankan restore.</p></div></div>{!isAdmin?<p className="mt-5 rounded-xl border border-slate-800 bg-slate-950 p-4 text-sm text-slate-500">Mode pengguna: fitur restore dinonaktifkan.</p>:<><input ref={inputRef} type="file" accept=".json,application/json" onChange={choose} className="hidden"/><button onClick={()=>inputRef.current?.click()} disabled={busy} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm font-semibold text-slate-200 hover:bg-slate-800 disabled:opacity-50"><FileUp size={17}/>Pilih Backup JSON</button>{backup&&<div className="mt-5 rounded-2xl border border-slate-800 bg-slate-950 p-4"><p className="font-semibold">{backup.workspace.name||'Workspace backup'}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><Count label="Akun" value={backup.accounts?.length}/><Count label="Kategori" value={backup.categories?.length}/><Count label="Transaksi" value={backup.transactions?.length}/><Count label="Transfer" value={backup.transfers?.length}/></div><div className="mt-4 space-y-2 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-xs leading-5 text-amber-300"><p className="flex items-start gap-2"><AlertTriangle size={15} className="mt-0.5 shrink-0"/>Restore diarahkan ke workspace aktif. Auth dan membership tidak dipulihkan.</p><p>Restore bersifat <b>additive/upsert</b>: data yang tidak ada di backup tidak dihapus.</p></div><button onClick={restore} disabled={busy} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-amber-600 px-4 py-3 text-sm font-semibold text-white hover:bg-amber-500 disabled:opacity-50">{busy?<RefreshCw size={17} className="animate-spin"/>:<CheckCircle2 size={17}/>} {busy?'Memulihkan...':'Konfirmasi Restore'}</button></div>}</>}{error&&<div role="alert" className="mt-4 rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}{message&&<div role="status" className="mt-4 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-300">{message}</div>}</section>
}
function Count({label,value}){return <div className="rounded-lg border border-slate-800 p-2"><span className="text-slate-600">{label}</span><b className="ml-2 text-slate-200">{value??0}</b></div>}
