import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Download, RefreshCw, TrendingDown, TrendingUp, Wallet } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { csvFromRows, getReportData, summarizeByAccount, summarizeByCategory } from '../../lib/reports'

const pad=n=>String(n).padStart(2,'0')
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-01`}
const today=()=>new Date().toISOString().slice(0,10)
const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0)
const dateLabel=v=>new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${v}T00:00:00`))

export default function Reports({user}){
 const [start,setStart]=useState(monthStart()),[end,setEnd]=useState(today()),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=async()=>{if(start>end)return setError('Periode tidak valid.');setLoading(true);setError('');try{setRows(await getReportData(user.id,start,end))}catch(e){setError(e.message||'Gagal memuat laporan.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[user.id])
 const summary=useMemo(()=>{const income=rows.filter(x=>x.transaction_type==='income').reduce((s,x)=>s+Number(x.amount),0);const expense=rows.filter(x=>x.transaction_type==='expense').reduce((s,x)=>s+Number(x.amount),0);return {income,expense,net:income-expense}},[rows])
 const chart=useMemo(()=>{const map={};rows.forEach(x=>{const k=x.transaction_date;(map[k]??={date:k,income:0,expense:0});map[k][x.transaction_type]+=Number(x.amount)});return Object.values(map).sort((a,b)=>a.date.localeCompare(b.date)).map(x=>({...x,label:x.date.slice(5)}))},[rows])
 const categories=useMemo(()=>summarizeByCategory(rows,'expense'),[rows])
 const accounts=useMemo(()=>summarizeByAccount(rows),[rows])
 const exportCsv=()=>{const blob=new Blob([csvFromRows(rows)],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`wsaku-laporan-${start}-${end}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
 const setPreset=(kind)=>{const now=new Date();let s,e=today();if(kind==='month')s=monthStart();else if(kind==='lastMonth'){const d=new Date(now.getFullYear(),now.getMonth()-1,1);s=`${d.getFullYear()}-${pad(d.getMonth()+1)}-01`;e=new Date(now.getFullYear(),now.getMonth(),0).toISOString().slice(0,10)}else{const d=new Date(now);d.setDate(d.getDate()-6);s=d.toISOString().slice(0,10)}setStart(s);setEnd(e)}
 return <main className="min-h-screen bg-slate-950 text-slate-100"><div className="mx-auto max-w-7xl px-4 py-6 pb-24 md:px-6 md:py-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-slate-500">Analitik Keuangan</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Laporan</h1><p className="mt-1 text-sm text-slate-500">Analisis pemasukan dan pengeluaran berdasarkan periode.</p></div><button onClick={exportCsv} disabled={!rows.length||loading} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-4 py-3 text-sm font-semibold transition hover:bg-slate-800 disabled:opacity-40"><Download size={17}/>Export CSV</button></div>
 <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-4 shadow-sm"><div className="flex flex-wrap gap-2 border-b border-slate-800 pb-4"><span className="mr-1 self-center text-xs font-semibold uppercase tracking-wide text-slate-500">Cepat</span><button onClick={()=>setPreset('week')} className="rounded-lg border border-slate-700 px-3 py-1.5 text-xs text-slate-300 hover:bg-slate-800">7 Hari</button><button onClick={()=>setPreset('month')} className="rounded-lg border border-slate-700 px-3 py-1.5 text-xs text-slate-300 hover:bg-slate-800">Bulan Ini</button><button onClick={()=>setPreset('lastMonth')} className="rounded-lg border border-slate-700 px-3 py-1.5 text-xs text-slate-300 hover:bg-slate-800">Bulan Lalu</button></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><label className="text-sm text-slate-400">Mulai<input type="date" value={start} max={end} onChange={e=>setStart(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-slate-100 outline-none focus:border-blue-500"/></label><label className="text-sm text-slate-400">Sampai<input type="date" value={end} min={start} onChange={e=>setEnd(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-slate-100 outline-none focus:border-blue-500"/></label><button onClick={load} disabled={loading} className="self-end rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold shadow-lg shadow-blue-950/20 transition hover:bg-blue-500 disabled:opacity-50"><RefreshCw size={17} className={loading?'inline animate-spin':'inline'}/> <span className="ml-1">{loading?'Memuat...':'Terapkan'}</span></button></div></section>
 {error&&<div role="alert" className="mt-4 rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}
 <section className="mt-6 grid gap-4 sm:grid-cols-3"><Card icon={Wallet} title="Arus Bersih" value={money(summary.net)} tone={summary.net<0?'negative':'neutral'}/><Card icon={TrendingUp} title="Total Pemasukan" value={money(summary.income)} tone="positive"/><Card icon={TrendingDown} title="Total Pengeluaran" value={money(summary.expense)} tone="negative"/></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-[1.6fr_1fr]"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-500/10 p-2.5 text-blue-300"><BarChart3 size={19}/></div><div><h2 className="font-semibold">Tren Arus Kas</h2><p className="text-xs text-slate-500">Per hari · {rows.length} transaksi</p></div></div><div className="mt-5 h-72">{chart.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:5,right:5,left:0,bottom:0}}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="label" stroke="#64748b" fontSize={11}/><YAxis stroke="#64748b" fontSize={11} tickFormatter={v=>v>=1000000?`${(v/1000000).toFixed(0)}jt`:v>=1000?`${(v/1000).toFixed(0)}rb`:v}/><Tooltip labelFormatter={v=>dateLabel(v)} formatter={v=>money(v)} contentStyle={{background:'#0f172a',border:'1px solid #334155',borderRadius:12}}/><Bar dataKey="income" name="Pemasukan" fill="#34d399" radius={[5,5,0,0]}/><Bar dataKey="expense" name="Pengeluaran" fill="#fb7185" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-slate-500">Tidak ada data pada periode ini.</div>}</div></div>
 <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Pengeluaran per Kategori</h2><p className="mt-1 text-xs text-slate-500">Kontribusi terhadap total biaya</p></div><span className="rounded-lg bg-rose-500/10 px-2 py-1 text-xs text-rose-300">{money(summary.expense)}</span></div><div className="mt-5 space-y-4">{categories.slice(0,8).map(x=><div key={x.id}><div className="flex items-center justify-between gap-3 text-sm"><span className="truncate">{x.name}</span><b className="shrink-0">{money(x.amount)}</b></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-rose-400 transition-all" style={{width:`${summary.expense?Math.min(100,x.amount/summary.expense*100):0}%`}}/></div></div>)}{!categories.length&&<p className="rounded-xl border border-dashed border-slate-800 py-8 text-center text-sm text-slate-600">Belum ada pengeluaran berkategori.</p>}</div></div></section>
 <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-5 shadow-sm"><div><h2 className="font-semibold">Ringkasan per Akun</h2><p className="mt-1 text-xs text-slate-500">Perubahan bersih selama periode terpilih</p></div><div className="mt-4 grid gap-3 md:grid-cols-2">{accounts.map(x=><div key={x.id} className="rounded-xl border border-slate-800/70 bg-slate-950/50 p-4 transition hover:border-slate-700"><div className="flex items-center justify-between gap-3"><span className="truncate font-medium">{x.name}</span><b className={x.net<0?'text-rose-400':'text-emerald-400'}>{x.net>0?'+':''}{money(x.net)}</b></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span>Pemasukan {money(x.income)}</span><span>Pengeluaran {money(x.expense)}</span></div></div>)}{!accounts.length&&<p className="text-sm text-slate-500">Belum ada transaksi pada periode ini.</p>}</div></section>
 <section className="mt-6 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900 shadow-sm"><div className="flex flex-col gap-2 border-b border-slate-800 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Detail Transaksi</h2><p className="mt-1 text-xs text-slate-500">{rows.length} transaksi · {start} sampai {end}</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-slate-800 bg-slate-950/40 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Tanggal</th><th className="px-4 py-3">Keterangan</th><th className="px-4 py-3">Kategori</th><th className="px-4 py-3">Akun</th><th className="px-4 py-3 text-right">Nominal</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-b border-slate-800/70 transition hover:bg-slate-950/50"><td className="whitespace-nowrap px-4 py-4 text-slate-400">{dateLabel(x.transaction_date)}</td><td className="max-w-[240px] truncate px-4 py-4">{x.description||'Transaksi'}</td><td className="px-4 py-4 text-slate-400">{x.categories?.name||'-'}</td><td className="px-4 py-4 text-slate-400">{x.cash_accounts?.name||'-'}</td><td className={`px-4 py-4 text-right font-semibold ${x.transaction_type==='income'?'text-emerald-400':'text-rose-400'}`}>{x.transaction_type==='income'?'+':'-'} {money(x.amount)}</td></tr>)}{!rows.length&&<tr><td colSpan="5" className="px-4 py-12 text-center text-slate-500">Tidak ada transaksi pada periode ini.</td></tr>}</tbody></table></div></section>
 </div></main>
}
function Card({icon:Icon,title,value,tone}){return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-slate-700"><div className="flex items-center gap-3"><div className={`rounded-xl p-3 ${tone==='positive'?'bg-emerald-500/10 text-emerald-300':tone==='negative'?'bg-rose-500/10 text-rose-300':'bg-blue-500/10 text-blue-300'}`}><Icon size={19}/></div><span className="text-sm text-slate-400">{title}</span></div><p className={`mt-4 text-xl font-bold ${tone==='positive'?'text-emerald-300':tone==='negative'?'text-rose-300':'text-slate-100'}`}>{value}</p></div>}
