import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Download, RefreshCw, TrendingDown, TrendingUp, Wallet } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { csvFromRows, getReportData, summarizeByAccount, summarizeByCategory } from '../../lib/reports'

const pad=n=>String(n).padStart(2,'0')
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-01`}
const today=()=>new Date().toISOString().slice(0,10)
const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0)

export default function Reports({user}){
 const [start,setStart]=useState(monthStart()),[end,setEnd]=useState(today()),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{setRows(await getReportData(user.id,start,end))}catch(e){setError(e.message||'Gagal memuat laporan.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[user.id])
 const summary=useMemo(()=>{const income=rows.filter(x=>x.transaction_type==='income').reduce((s,x)=>s+Number(x.amount),0);const expense=rows.filter(x=>x.transaction_type==='expense').reduce((s,x)=>s+Number(x.amount),0);return {income,expense,net:income-expense}},[rows])
 const chart=useMemo(()=>{const map={};rows.forEach(x=>{const k=x.transaction_date;(map[k]??={date:k,income:0,expense:0});map[k][x.transaction_type]+=Number(x.amount)});return Object.values(map).sort((a,b)=>a.date.localeCompare(b.date)).map(x=>({...x,label:x.date.slice(5)}))},[rows])
 const categories=useMemo(()=>summarizeByCategory(rows,'expense'),[rows])
 const accounts=useMemo(()=>summarizeByAccount(rows),[rows])
 const exportCsv=()=>{const blob=new Blob([csvFromRows(rows)],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`wsaku-laporan-${start}-${end}.csv`;a.click();URL.revokeObjectURL(url)}
 return <main className="min-h-screen bg-slate-950 text-slate-100"><div className="mx-auto max-w-7xl px-4 py-6 md:px-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-slate-500">Analitik Keuangan</p><h1 className="text-2xl font-bold">Laporan</h1><p className="mt-1 text-sm text-slate-500">Ringkasan keuangan berdasarkan periode yang dipilih.</p></div><button onClick={exportCsv} disabled={!rows.length} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 px-4 py-3 text-sm font-semibold disabled:opacity-40"><Download size={17}/>Export CSV</button></div>
 <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><label className="text-sm text-slate-400">Mulai<input type="date" value={start} max={end} onChange={e=>setStart(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-slate-100"/></label><label className="text-sm text-slate-400">Sampai<input type="date" value={end} min={start} onChange={e=>setEnd(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-slate-100"/></label><button onClick={load} disabled={loading} className="self-end rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold disabled:opacity-50"><RefreshCw size={17} className={loading?'inline animate-spin':'inline'}/> <span className="ml-1">Terapkan</span></button></div></section>
 {error&&<div className="mt-4 rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}
 <section className="mt-6 grid gap-4 sm:grid-cols-3"><Card icon={Wallet} title="Arus Bersih" value={money(summary.net)}/><Card icon={TrendingUp} title="Pemasukan" value={money(summary.income)}/><Card icon={TrendingDown} title="Pengeluaran" value={money(summary.expense)}/></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-[1.6fr_1fr]"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center gap-2"><BarChart3 size={19}/><div><h2 className="font-semibold">Tren Arus Kas</h2><p className="text-xs text-slate-500">Per hari dalam periode terpilih</p></div></div><div className="mt-5 h-72">{chart.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="label" stroke="#64748b" fontSize={11}/><YAxis stroke="#64748b" fontSize={11}/><Tooltip formatter={v=>money(v)} contentStyle={{background:'#0f172a',border:'1px solid #334155'}}/><Bar dataKey="income" name="Pemasukan" fill="#34d399" radius={[5,5,0,0]}/><Bar dataKey="expense" name="Pengeluaran" fill="#fb7185" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-slate-500">Tidak ada data pada periode ini.</div>}</div></div>
 <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Pengeluaran per Kategori</h2><div className="mt-4 space-y-3">{categories.slice(0,8).map(x=><div key={x.id}><div className="flex justify-between text-sm"><span>{x.name}</span><b>{money(x.amount)}</b></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-rose-400" style={{width:`${summary.expense?Math.min(100,x.amount/summary.expense*100):0}%`}}/></div></div>)}{!categories.length&&<p className="text-sm text-slate-500">Belum ada pengeluaran berkategori.</p>}</div></div></section>
 <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Ringkasan per Akun</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{accounts.map(x=><div key={x.id} className="rounded-xl bg-slate-950/60 p-4"><div className="flex justify-between"><span className="font-medium">{x.name}</span><b className={x.net<0?'text-rose-400':'text-emerald-400'}>{money(x.net)}</b></div><div className="mt-2 flex gap-4 text-xs text-slate-500"><span>Pemasukan {money(x.income)}</span><span>Pengeluaran {money(x.expense)}</span></div></div>)}{!accounts.length&&<p className="text-sm text-slate-500">Belum ada transaksi pada periode ini.</p>}</div></section>
 <section className="mt-6 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-5"><h2 className="font-semibold">Detail Transaksi</h2><p className="text-xs text-slate-500">{rows.length} transaksi</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Tanggal</th><th className="px-4 py-3">Keterangan</th><th className="px-4 py-3">Kategori</th><th className="px-4 py-3">Akun</th><th className="px-4 py-3 text-right">Nominal</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-b border-slate-800/70"><td className="px-4 py-4 text-slate-400">{x.transaction_date}</td><td className="px-4 py-4">{x.description||'Transaksi'}</td><td className="px-4 py-4 text-slate-400">{x.categories?.name||'-'}</td><td className="px-4 py-4 text-slate-400">{x.cash_accounts?.name||'-'}</td><td className={`px-4 py-4 text-right font-semibold ${x.transaction_type==='income'?'text-emerald-400':'text-rose-400'}`}>{x.transaction_type==='income'?'+':'-'} {money(x.amount)}</td></tr>)}{!rows.length&&<tr><td colSpan="5" className="px-4 py-10 text-center text-slate-500">Tidak ada transaksi.</td></tr>}</tbody></table></div></section>
 </div></main>
}
function Card({icon:Icon,title,value}){return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-slate-800 p-3"><Icon size={19}/></div><span className="text-sm text-slate-400">{title}</span></div><p className="mt-4 text-xl font-bold">{value}</p></div>}
