import { useEffect, useState } from 'react'
import { Banknote, Edit3, Folder, Plus, RefreshCw, Tags, WalletCards, X } from 'lucide-react'
import { getMasterData, saveAccount, saveCategory } from '../../lib/masterData'

const money = v => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0)
const blankAccount = { id:null,name:'',type:'cash',openingBalance:'0',active:true }
const blankCategory = { id:null,name:'',type:'expense' }

export default function MasterData({ user }) {
  const [data,setData]=useState({accounts:[],categories:[]}),[tab,setTab]=useState('accounts'),[modal,setModal]=useState(null),[form,setForm]=useState(blankAccount),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const load=async()=>{setLoading(true);setError('');try{setData(await getMasterData(user.id))}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[user.id])
  const openAccount=(item=null)=>{setForm(item?{id:item.id,name:item.name,type:item.account_type,openingBalance:item.opening_balance,active:item.is_active}:blankAccount);setModal('account')}
  const openCategory=(item=null)=>{setForm(item?{id:item.id,name:item.name,type:item.category_type}:blankCategory);setModal('category')}
  const submit=async e=>{e.preventDefault();if(!form.name.trim())return setError('Nama wajib diisi.');setSaving(true);setError('');try{if(modal==='account')await saveAccount({userId:user.id,...form});else await saveCategory({userId:user.id,...form});setModal(null);await load()}catch(err){setError(err.message||'Gagal menyimpan data.')}finally{setSaving(false)}}
  const field='mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-slate-100 outline-none focus:border-blue-500'
  if(loading)return <div className="grid min-h-screen place-items-center bg-slate-950 text-slate-400"><RefreshCw className="animate-spin"/></div>
  return <main className="min-h-screen bg-slate-950 text-slate-100"><div className="mx-auto max-w-7xl px-4 py-6 md:px-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-slate-500">Master Data</p><h1 className="text-2xl font-bold">Akun & Kategori</h1><p className="mt-1 text-sm text-slate-500">Kelola data dasar workspace keuangan</p></div><button onClick={()=>tab==='accounts'?openAccount():openCategory()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold"><Plus size={18}/>Tambah {tab==='accounts'?'Akun':'Kategori'}</button></div>
  <div className="mt-6 flex gap-2 rounded-2xl border border-slate-800 bg-slate-900 p-2"><button onClick={()=>setTab('accounts')} className={`flex flex-1 items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold ${tab==='accounts'?'bg-blue-600 text-white':'text-slate-400'}`}><WalletCards size={17}/>Akun Keuangan</button><button onClick={()=>setTab('categories')} className={`flex flex-1 items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold ${tab==='categories'?'bg-blue-600 text-white':'text-slate-400'}`}><Tags size={17}/>Kategori</button></div>
  {error&&<div className="mt-4 rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}
  {tab==='accounts'?<section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.accounts.map(a=><div key={a.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between"><div className="flex gap-3"><div className="rounded-xl bg-blue-500/10 p-3 text-blue-300"><Banknote size={20}/></div><div><h3 className="font-semibold">{a.name}</h3><p className="mt-1 text-xs capitalize text-slate-500">{a.account_type} · {a.is_active?'Aktif':'Nonaktif'}</p></div></div><button onClick={()=>openAccount(a)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800"><Edit3 size={16}/></button></div><p className="mt-6 text-lg font-bold">{money(a.opening_balance)}</p><p className="mt-1 text-xs text-slate-500">Saldo awal</p></div>)}{!data.accounts.length&&<Empty text="Belum ada akun keuangan."/>}</section>:<section className="mt-6 grid gap-4 md:grid-cols-2">{['income','expense'].map(type=><div key={type} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">{type==='income'?'Pemasukan':'Pengeluaran'}</h2><p className="text-xs text-slate-500">Kategori {type==='income'?'pendapatan':'biaya'}</p></div><button onClick={()=>{setForm({...blankCategory,type});setModal('category')}} className="rounded-xl bg-blue-600 p-2"><Plus size={17}/></button></div><div className="mt-4 space-y-2">{data.categories.filter(c=>c.category_type===type).map(c=><div key={c.id} className="flex items-center justify-between rounded-xl bg-slate-950/60 px-3 py-3"><span className="flex items-center gap-2 text-sm"><Folder size={15} className="text-slate-500"/>{c.name}</span><button onClick={()=>openCategory(c)} className="text-slate-400"><Edit3 size={15}/></button></div>)}{!data.categories.some(c=>c.category_type===type)&&<p className="py-5 text-center text-sm text-slate-600">Belum ada kategori.</p>}</div></div>)}</section>}
  </div>{modal&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="w-full max-w-md rounded-3xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">{modal==='account'?'Akun Keuangan':'Kategori'}</h2><button onClick={()=>setModal(null)}><X size={19}/></button></div><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm text-slate-300">Nama<input required maxLength="100" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={field}/></label>{modal==='account'?<><label className="block text-sm text-slate-300">Jenis<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className={field}><option value="cash">Kas</option><option value="bank">Bank</option><option value="ewallet">E-Wallet</option><option value="other">Lainnya</option></select></label><label className="block text-sm text-slate-300">Saldo Awal<input type="number" min="0" step="0.01" value={form.openingBalance} onChange={e=>setForm({...form,openingBalance:e.target.value})} className={field}/></label><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Akun aktif</label></>:<label className="block text-sm text-slate-300">Jenis<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className={field}><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select></label>}<button disabled={saving} className="w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold disabled:opacity-50">{saving?'Menyimpan...':'Simpan'}</button></form></div></div>}</main>
}
function Empty({text}){return <div className="rounded-2xl border border-dashed border-slate-800 p-8 text-center text-sm text-slate-500">{text}</div>}
