import { useEffect, useMemo, useState } from 'react'
import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight, CheckCircle2, X } from 'lucide-react'
import { createTransaction, createTransfer, getTransactionFormData } from '../../lib/transactions'

const today = () => new Date().toISOString().slice(0, 10)
const empty = { type: 'expense', accountId: '', categoryId: '', fromAccountId: '', toAccountId: '', date: today(), amount: '', description: '' }

export default function TransactionModal({ user, onClose, onSaved }) {
  const [form, setForm] = useState(empty), [data, setData] = useState({ accounts: [], categories: [] }), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState('')
  useEffect(() => { getTransactionFormData(user.id).then(setData).catch(err => setError(err.message)).finally(() => setLoading(false)) }, [user.id])
  const categories = useMemo(() => data.categories.filter(x => x.category_type === form.type), [data.categories, form.type])
  const set = (key, value) => setForm(prev => ({ ...prev, [key]: value }))
  const submit = async (event) => { event.preventDefault(); setError(''); if (!form.amount || Number(form.amount) <= 0) return setError('Nominal harus lebih dari 0.'); if (form.type === 'transfer' && (!form.fromAccountId || !form.toAccountId || form.fromAccountId === form.toAccountId)) return setError('Pilih akun sumber dan tujuan yang berbeda.'); setSaving(true); try { if (form.type === 'transfer') await createTransfer({ userId:user.id, fromAccountId:form.fromAccountId, toAccountId:form.toAccountId, date:form.date, amount:form.amount, description:form.description }); else await createTransaction({ userId:user.id, type:form.type, accountId:form.accountId, categoryId:form.categoryId, date:form.date, amount:form.amount, description:form.description }); onSaved(); onClose() } catch(err) { setError(err.message || 'Gagal menyimpan transaksi.') } finally { setSaving(false) } }
  const field = 'mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-slate-100 outline-none transition placeholder:text-slate-600 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/10'
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/75 p-3 backdrop-blur-sm sm:grid sm:place-items-center sm:p-4"><div className="mx-auto mt-8 w-full max-w-lg overflow-hidden rounded-3xl border border-slate-800 bg-slate-900 shadow-2xl sm:mt-0">
    <div className="flex items-center justify-between border-b border-slate-800 px-5 py-4 sm:px-6"><div><div className="flex items-center gap-2"><span className="rounded-lg bg-blue-500/10 p-1.5 text-blue-400"><CheckCircle2 size={16}/></span><h2 className="font-semibold">Transaksi Baru</h2></div><p className="mt-1 text-xs text-slate-500">Catat aktivitas keuangan dengan cepat</p></div><button aria-label="Tutup" onClick={onClose} className="rounded-xl p-2 text-slate-400 transition hover:bg-slate-800 hover:text-white"><X size={19}/></button></div>
    <form onSubmit={submit} className="space-y-5 p-5 sm:p-6"><div className="grid grid-cols-3 gap-2 rounded-2xl bg-slate-950/60 p-1.5">{[['expense','Pengeluaran',ArrowUpRight],['income','Pemasukan',ArrowDownLeft],['transfer','Transfer',ArrowLeftRight]].map(([value,label,Icon]) => <button type="button" key={value} onClick={()=>set('type',value)} className={`flex items-center justify-center gap-1.5 rounded-xl px-2 py-3 text-xs font-semibold transition sm:gap-2 ${form.type===value?'bg-blue-600 text-white shadow-lg shadow-blue-950/30':'text-slate-500 hover:bg-slate-800 hover:text-slate-200'}`}><Icon size={16}/><span>{label}</span></button>)}</div>
      {loading ? <div className="rounded-2xl border border-dashed border-slate-800 py-12 text-center text-sm text-slate-500">Memuat akun dan kategori...</div> : <>
        {form.type !== 'transfer' ? <div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-300">Akun<select required value={form.accountId} onChange={e=>set('accountId',e.target.value)} className={field}><option value="">Pilih akun</option>{data.accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block text-sm font-medium text-slate-300">Kategori<select value={form.categoryId} onChange={e=>set('categoryId',e.target.value)} className={field}><option value="">Tanpa kategori</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div> : <div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-300">Dari<select required value={form.fromAccountId} onChange={e=>set('fromAccountId',e.target.value)} className={field}><option value="">Akun sumber</option>{data.accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block text-sm font-medium text-slate-300">Ke<select required value={form.toAccountId} onChange={e=>set('toAccountId',e.target.value)} className={field}><option value="">Akun tujuan</option>{data.accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>}
        <div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-300">Tanggal<input required type="date" value={form.date} onChange={e=>set('date',e.target.value)} className={field}/></label><label className="block text-sm font-medium text-slate-300">Nominal<input required min="1" step="0.01" inputMode="decimal" type="number" value={form.amount} onChange={e=>set('amount',e.target.value)} placeholder="0" className={field}/></label></div>
        <label className="block text-sm font-medium text-slate-300">Keterangan<textarea value={form.description} onChange={e=>set('description',e.target.value)} rows="3" maxLength="500" placeholder="Contoh: Belanja kebutuhan rumah" className={field}/><span className="mt-1 block text-right text-[11px] text-slate-600">Opsional · maksimal 500 karakter</span></label>
      </>}
      {error && <div role="alert" className="rounded-xl border border-rose-500/20 bg-rose-500/10 px-3 py-3 text-sm leading-5 text-rose-300">{error}</div>}
      <div className="flex flex-col-reverse gap-2 pt-1 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="rounded-xl border border-slate-700 px-4 py-3 text-sm font-medium text-slate-300 transition hover:bg-slate-800">Batal</button><button disabled={saving||loading} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-950/20 transition hover:bg-blue-500 disabled:cursor-not-allowed disabled:opacity-50">{saving?'Menyimpan...':'Simpan Transaksi'}</button></div>
    </form></div></div>
}
